name: Build iOS IPA

on:
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - master
    paths:
      - 'lib/**'
      - 'ios/**'
      - 'pubspec.yaml'
      - '.github/workflows/**'

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS App (No Codesign)
        run: flutter build ios --release --no-codesign

      - name: Package IPA
        run: |
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -r numerical.ipa Payload
          
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: numerical-ios-app
          path: numerical.ipa
